return {
  ["a"] = { "<cmd>Dashboard<cr>", "Dashboard" },
  b = {
    name = "Buffers",
    c = { "<cmd>w! <bar> %bd! <bar> e# <bar> bd# <CR>", "Close All Buffers" }
  },
  ["e"] = { "<cmd>Neotree toggle<cr>", "Explorer" },
  ["r"] = { "<cmd>:Telescope oldfiles hidden=true<CR>", "Recent Files" },
  ["w"] = { "<cmd>w<CR>", "Save" },
  ["vs"] = { "<cmd>vsp<cr>", "Split" },
  v = {
    name = "Splits",
    s = { "<cmd>vsp<cr>", "Vertical" },
    c = { "<cmd>on<cr>", "Close all splits" }
  },
  ["q"] = { "<cmd>q!<CR>", "Quit" },
  ["c"] = { "<cmd>bdelete<CR>", "Close Buffer" },
  ["h"] = { "<cmd>nohlsearch<CR>", "No Highlight" },
  ["f"] = { "<cmd>Telescope find_files<cr>", "Find Files" },
  ["F"] = { "<cmd>Telescope live_grep<cr>", "Find Text" },
  g = {
    name = "Git",
    c = { "<cmd>Git commit<cr>", "Make Commit" },
    a = { "<cmd>Git add .<cr>", "Add files" },
    p = { "<cmd>Git push<cr>", "Push Changes" },
    o = { "<cmd>Telescope git_status<cr>", "Search changed files" },
    b = { "<cmd>Telescope git_branches<cr>", "Search Branch" },
    q = { "<cmd>Telescope git_commits<cr>", "Search Commits" },
    d = {
      "<cmd>Gitsigns diffthis HEAD<cr>",
      "Diff",
    },
  },
  l = {
    name = "LSP",
    a = { "<cmd>lua vim.lsp.buf.code_action()<cr>", "Code Action" },
    d = {
      "<cmd>Telescope lsp_document_diagnostics<cr>",
      "Document Diagnostics",
    },
    w = {
      "<cmd>Telescope lsp_workspace_diagnostics<cr>",
      "Workspace Diagnostics",
    },
    f = { "<cmd>lua vim.lsp.buf.format()<cr>", "Format" },
    i = { "<cmd>LspInfo<cr>", "Info" },
    I = { "<cmd>LspInstallInfo<cr>", "Installer Info" },
    j = {
      "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>",
      "Next Diagnostic",
    },
    k = {
      "<cmd>lua vim.lsp.diagnostic.goto_prev()<cr>",
      "Prev Diagnostic",
    },
    l = { "<cmd>lua vim.lsp.codelens.run()<cr>", "CodeLens Action" },
    q = { "<cmd>lua vim.lsp.diagnostic.set_loclist()<cr>", "Quickfix" },
    r = { "<cmd>lua vim.lsp.buf.rename()<cr>", "Rename" },
    s = { "<cmd>Lspsaga show_line_diagnostics<CR>", "See Diagnostics" },
    S = {
      "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>",
      "Workspace Symbols",
    },
  },
  s = {
    name = "Search",
    b = { "<cmd>Telescope git_branches<cr>", "Checkout branch" },
    c = { "<cmd>Telescope colorscheme<cr>", "Colorscheme" },
    h = { "<cmd>Telescope help_tags<cr>", "Find Help" },
    M = { "<cmd>Telescope man_pages<cr>", "Man Pages" },
    r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File" },
    R = { "<cmd>Telescope registers<cr>", "Registers" },
    k = { "<cmd>Telescope keymaps<cr>", "Keymaps" },
    C = { "<cmd>Telescope commands<cr>", "Commands" },
  },
  t = {
    name = "Terminal",
    n = { "<cmd>lua _NODE_TOGGLE()<cr>", "Node" },
    u = { "<cmd>lua _NCDU_TOGGLE()<cr>", "NCDU" },
    t = { "<cmd>lua _HTOP_TOGGLE()<cr>", "Htop" },
    p = { "<cmd>lua _PYTHON_TOGGLE()<cr>", "Python" },
    g = { "<cmd>lua _GIT_BASH_TOGGLE()<cr>", "Git Bash" },
    f = { "<cmd>ToggleTerm direction=float<cr>", "Float" },
    h = { "<cmd>ToggleTerm size=10 direction=horizontal<cr>", "Horizontal" },
    v = { "<cmd>ToggleTerm size=80 direction=vertical<cr>", "Vertical" },
  },
}
